#!/usr/bin/env bats
# orca.sh decisions — deterministic decision-log render from trunk history.

load helpers

decisions() { bash "$SCRIPTS/orca.sh" decisions "$@"; }

# commit_with_body <repo> <file> <subject> <body...> — one commit whose
# body is the remaining lines.
commit_with_body() {
  local repo="$1" file="$2" subject="$3"
  shift 3
  echo "content-$RANDOM" >"$repo/$file"
  git -C "$repo" add -A
  local msg="$subject"
  local line
  for line in "$@"; do
    msg="$msg
$line"
  done
  git -C "$repo" commit -qm "$msg"
}

@test "render extracts canonical bullets newest first with sha-derived ids" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  commit_with_body "$r" a.txt "feat: first" "" "- chose alpha over beta: alpha is simpler"
  commit_with_body "$r" b.txt "feat: second" "" "- chose gamma over delta: delta could not scale"
  sha1="$(git -C "$r" log --format=%h --grep 'first')"
  sha2="$(git -C "$r" log --format=%h --grep 'second')"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'WROTE:\t'"$r/.orca/decisions.md"
  has_line $'ENTRIES:\t2'
  has_line $'TIP:\t'"$sha2"
  has_line $'ARCHIVE:\tabsent'
  grep -q "^- \*\*D-$sha1\*\* (.*feat: first): chose alpha over beta: alpha is simpler$" "$r/.orca/decisions.md"
  grep -q "^- \*\*D-$sha2\*\*" "$r/.orca/decisions.md"
  # Newest first: second's entry line precedes first's.
  [ "$(grep -n "D-$sha2" "$r/.orca/decisions.md" | head -1 | cut -d: -f1)" -lt \
    "$(grep -n "D-$sha1" "$r/.orca/decisions.md" | head -1 | cut -d: -f1)" ]
  grep -q '^\*\*As of:\*\* '"$sha2" "$r/.orca/decisions.md"
  grep -q 'generated by `orca.sh decisions render`' "$r/.orca/decisions.md"
}

@test "full walk finds bullets behind a landing merge's second parent" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  git -C "$r" checkout -qb feature/x
  commit_with_body "$r" item.txt "feat: item work" "" "- chose queue over poll: poll wakes idle workers"
  git -C "$r" checkout -q main
  git -C "$r" merge -q --no-ff -m "land feature/x" feature/x
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t1'
  grep -q 'chose queue over poll: poll wakes idle workers' "$r/.orca/decisions.md"
}

@test "unmerged branch bullets stay invisible to a trunk render" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  git -C "$r" checkout -qb feature/unlanded
  commit_with_body "$r" u.txt "feat: unlanded" "" "- chose leak over none: should not appear"
  git -C "$r" checkout -q main
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t0'
  ! grep -q 'should not appear' "$r/.orca/decisions.md"
}

@test "a multi-bullet commit suffixes later ids in body order" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  commit_with_body "$r" m.txt "feat: two choices" "" \
    "- chose one over two: first reason" \
    "- chose three over four: second reason"
  sha="$(git -C "$r" log -1 --format=%h)"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t2'
  grep -q "^- \*\*D-$sha\*\* .*: chose one over two: first reason$" "$r/.orca/decisions.md"
  grep -q "^- \*\*D-$sha-2\*\* .*: chose three over four: second reason$" "$r/.orca/decisions.md"
}

@test "unprefixed bullets match; mid-sentence and subject-line 'chose' do not" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  commit_with_body "$r" p.txt "chose subject over body: never scanned" "" \
    "chose bare over dashed: history carries both spellings" \
    "we chose this over that: prose, not a bullet"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t1'
  grep -q 'chose bare over dashed: history carries both spellings' "$r/.orca/decisions.md"
  ! grep -q 'never scanned' "$r/.orca/decisions.md"
  ! grep -q 'prose, not a bullet' "$r/.orca/decisions.md"
}

@test "no bullets renders a headed empty file" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t0'
  grep -q '^# Decision log$' "$r/.orca/decisions.md"
  grep -q '^\*\*As of:\*\*' "$r/.orca/decisions.md"
  ! grep -q '^- \*\*D-' "$r/.orca/decisions.md"
}

@test "an archive file is appended verbatim under an Archived heading" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  mkdir -p "$r/.orca"
  printf '# Decision log\n\n- **D92** (2026-08-13): chose old over older: frozen entry\n' \
    >"$r/.orca/decisions.archive.md"
  commit_with_body "$r" a.txt "feat: fresh" "" "- chose new over old: fresh entry"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ARCHIVE:\tincluded'
  grep -q '^## Archived$' "$r/.orca/decisions.md"
  grep -q 'chose old over older: frozen entry' "$r/.orca/decisions.md"
  # Generated entries precede the archive section.
  [ "$(grep -n 'fresh entry' "$r/.orca/decisions.md" | cut -d: -f1)" -lt \
    "$(grep -n '^## Archived$' "$r/.orca/decisions.md" | cut -d: -f1)" ]
}

@test "render is idempotent and overwrites a stale render" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  commit_with_body "$r" a.txt "feat: one" "" "- chose a over b: reason"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  first="$(cat "$r/.orca/decisions.md")"
  commit_with_body "$r" b.txt "feat: two" "" "- chose c over d: reason"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t2'
  [ "$first" != "$(cat "$r/.orca/decisions.md")" ]
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t2'
}

@test "conventional checkout gets .orca/ into info/exclude" {
  make_repo "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  grep -qxF '.orca/' "$r/.git/info/exclude"
}

@test "works against the bare-with-worktrees layout" {
  make_bare_layout "$BATS_TEST_TMPDIR/r"
  r="$BATS_TEST_TMPDIR/r"
  commit_with_body "$r/main" w.txt "feat: in worktree" "" "- chose x over y: bare layout entry"
  run decisions render "$r" --trunk main
  [ "$status" -eq 0 ]
  has_line $'ENTRIES:\t1'
  grep -q 'bare layout entry' "$r/.orca/decisions.md"
}

@test "typed failures: bad args, not git, unknown trunk" {
  run decisions render
  [ "$status" -eq 1 ]
  has_line $'FAIL:\tBAD_ARGS'
  make_repo "$BATS_TEST_TMPDIR/r"
  run decisions render "$BATS_TEST_TMPDIR/r"
  [ "$status" -eq 1 ]
  has_line $'FAIL:\tBAD_ARGS'
  mkdir -p "$BATS_TEST_TMPDIR/notgit"
  run decisions render "$BATS_TEST_TMPDIR/notgit" --trunk main
  [ "$status" -eq 1 ]
  has_line $'FAIL:\tNOT_GIT'
  run decisions render "$BATS_TEST_TMPDIR/r" --trunk nope
  [ "$status" -eq 1 ]
  has_line $'FAIL:\tUNKNOWN_TRUNK'
  run decisions frobnicate "$BATS_TEST_TMPDIR/r" --trunk main
  [ "$status" -eq 1 ]
  has_line $'FAIL:\tBAD_ARGS'
}
